/* tslint:disable */
/* eslint-disable */
/**
 * s
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AnyType,
    AnyTypeFromJSON,
    AnyTypeFromJSONTyped,
    AnyTypeToJSON,
} from './AnyType';

/**
 * 
 * @export
 * @interface DeliveryOrder
 */
export interface DeliveryOrder {
    /**
     * 
     * @type {string}
     * @memberof DeliveryOrder
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryOrder
     */
    purchaseId?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryOrder
     */
    providerId?: DeliveryOrderProviderIdEnum;
    /**
     * 
     * @type {string}
     * @memberof DeliveryOrder
     */
    deliveryMethodId?: DeliveryOrderDeliveryMethodIdEnum;
    /**
     * 
     * @type {Array<any>}
     * @memberof DeliveryOrder
     */
    option: Array<any>;
    /**
     * 
     * @type {Date}
     * @memberof DeliveryOrder
     */
    orderAt?: Date;
}


/**
 * @export
 */
export const DeliveryOrderProviderIdEnum = {
    doraemon: 'doraemon',
    gundam: 'gundam'
} as const;
export type DeliveryOrderProviderIdEnum = typeof DeliveryOrderProviderIdEnum[keyof typeof DeliveryOrderProviderIdEnum];

/**
 * @export
 */
export const DeliveryOrderDeliveryMethodIdEnum = {
    dora: 'dora',
    gufu: 'gufu',
    gundam: 'gundam',
    suneo: 'suneo'
} as const;
export type DeliveryOrderDeliveryMethodIdEnum = typeof DeliveryOrderDeliveryMethodIdEnum[keyof typeof DeliveryOrderDeliveryMethodIdEnum];


export function DeliveryOrderFromJSON(json: any): DeliveryOrder {
    return DeliveryOrderFromJSONTyped(json, false);
}

export function DeliveryOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'purchaseId': !exists(json, 'purchaseId') ? undefined : json['purchaseId'],
        'providerId': !exists(json, 'providerId') ? undefined : json['providerId'],
        'deliveryMethodId': !exists(json, 'deliveryMethodId') ? undefined : json['deliveryMethodId'],
        'option': ((json['option'] as Array<any>).map(anyFromJSON)),
        'orderAt': !exists(json, 'orderAt') ? undefined : (new Date(json['orderAt'])),
    };
}

export function DeliveryOrderToJSON(value?: DeliveryOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'purchaseId': value.purchaseId,
        'providerId': value.providerId,
        'deliveryMethodId': value.deliveryMethodId,
        'option': ((value.option as Array<any>).map(anyToJSON)),
        'orderAt': value.orderAt === undefined ? undefined : (value.orderAt.toISOString()),
    };
}

