/* tslint:disable */
/* eslint-disable */
/**
 * s
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NormalOption
 */
export interface NormalOption {
    /**
     * 
     * @type {string}
     * @memberof NormalOption
     */
    optionTag?: NormalOptionOptionTagEnum;
    /**
     * 
     * @type {string}
     * @memberof NormalOption
     */
    name?: NormalOptionNameEnum;
    /**
     * 
     * @type {boolean}
     * @memberof NormalOption
     */
    okihai?: boolean;
}


/**
 * @export
 */
export const NormalOptionOptionTagEnum = {
    Normal: 'Normal'
} as const;
export type NormalOptionOptionTagEnum = typeof NormalOptionOptionTagEnum[keyof typeof NormalOptionOptionTagEnum];

/**
 * @export
 */
export const NormalOptionNameEnum = {
    : '通常オプション'
} as const;
export type NormalOptionNameEnum = typeof NormalOptionNameEnum[keyof typeof NormalOptionNameEnum];


export function NormalOptionFromJSON(json: any): NormalOption {
    return NormalOptionFromJSONTyped(json, false);
}

export function NormalOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NormalOption {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'optionTag': !exists(json, 'optionTag') ? undefined : json['optionTag'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'okihai': !exists(json, 'okihai') ? undefined : json['okihai'],
    };
}

export function NormalOptionToJSON(value?: NormalOption | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'optionTag': value.optionTag,
        'name': value.name,
        'okihai': value.okihai,
    };
}

